default: {{ juju_default_env_name }}
environments:
  {{ juju_default_env_name }}:
    admin-secret: {{ osm_pass }}
    bootstrap-host: {{ floating_ip }}
    bootstrap-user: {{ osm_user }}
    default-series: trusty
    type: manual
    enable-os-refresh-update: False
    enable-os-upgrade: False

    # Proxy settings set via juju_proxy_environments.sh
