---
openstack:
  connection:
    username: admin
    password: cable123
    auth_url: http://10.197.123.50:5000/v2.0/
    tenant_name: admin
    http_proxy:
  images:
    - image:
        name: Centos 7
        format: qcow2
        download_url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
        local_download_path: /tmp/create_image_tests
    - image:
        name: Cirros
        format: qcow2
        download_url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
        local_download_path: /tmp/create_image_tests
  networks:
    - network:
        name: manager-ext-net
        subnet:
          name: manager-ext-subnet
          cidr: 10.0.1.0/24
        router:
          name: manager-ext-router
          external_gateway: external
    - network:
        name: manager-int-net
        subnet:
          name: manager-int-subnet
          cidr: 10.1.1.0/24
        router:
          name: manager-int-router
    - network:
        name: site1-net
        subnet:
          name: site1-subnet
          cidr: 10.0.2.0/24
          gateway_ip: 10.0.2.1
        router:
          name: site1-router
    - network:
        name: site2-net
        subnet:
          name: site2-subnet
          cidr: 10.0.3.0/24
          gateway_ip: 10.0.3.1
        router:
          name: site2-router
    - network:
        name: ent1-net
        subnet:
          name: ent1-subnet
          cidr: 192.168.1.0/24
          gateway_ip: 192.168.1.1
        router:
          name: ent1-router
    - network:
        name: ent2-net
        subnet:
          name: ent2-subnet
          cidr: 192.168.1.0/24
          gateway_ip: 192.168.1.1
        router:
          name: ent2-router
  keypairs:
    - keypair:
        name: unimgr
        public_filepath: /tmp/unimgr.pub
        private_filepath: /tmp/unimgr
  instances:
    - instance:
        name: mgr-app
        flavor: m1.small
        imageName: Centos 7
        keypair_name: unimgr
        ports:
          - port:
              name: manager-ext-port
              network_name: manager-ext-net
          - port:
              name: manager-int-port1
              network_name: manager-int-net
        floating_ip:
          ext_net: external
          port_name: manager-ext-port
    - instance:
        name: mgr-srvc
        flavor: m1.small
        imageName: Centos 7
        keypair_name: unimgr
        ports:
          - port:
              name: manager-int-port2
              network_name: manager-int-net
    - instance:
        name: mgr-odl
        flavor: m1.small
        imageName: Centos 7
        keypair_name: unimgr
        ports:
          - port:
              name: manager-int-port
              network_name: manager-int-net
    - instance:
        name: site1-ovs
        flavor: m1.small
        imageName: Centos 7
        keypair_name: unimgr
        ports:
          - port:
              name: site1-port
              network_name: site1-net
    - instance:
        name: site1-host
        flavor: m1.small
        imageName: Cirros
        keypair_name: unimgr
        ports:
          - port:
              name: site1-host
              network_name: site1-net
          - port:
              name: ent1-host
              network_name: ent1-net
    - instance:
        name: site2-ovs
        flavor: m1.small
        imageName: Centos 7
        keypair_name: unimgr
        ports:
          - port:
              name: site2-port
              network_name: site2-net
    - instance:
        name: site2-host
        flavor: m1.small
        imageName: Cirros
        keypair_name: unimgr
        ports:
          - port:
              name: site2-host
              network_name: site2-net
          - port:
              name: ent2-host
              network_name: ent2-net
