---
- hosts: all
  remote_user: vbcpe
  become: yes
  become_user: root

  tasks:
   - name: Transfer the script
     copy: src=~/Downloads/new_ansible/installJavaMavenTomcat.sh dest=/home/vbcpe/installJavaMavenTomcat.sh mode=0777

   - name: Execute the script
     command: sh /home/vbcpe/installJavaMavenTomcat.sh

