---
- include: ../openvswitch/main.yml
- include: playbooks/required_packages.yml
- include: playbooks/optional_packages.yml
- include: playbooks/install_proxy.yml
- include: playbooks/install_apex.yml
