---
openstack:
  connection:
    username: admin
    password: octopus
    auth_url: http://10.197.123.37:5000/v2.0
    tenant_name: admin
  image:
    name: Centos 7
    format: qcow2
    download_url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1503.qcow2
    local_download_path: /tmp/create_image_tests
  networks:
    - network:
        name: public
        subnet:
          name: cmts-pub-subnet
          cidr: 10.197.122.0/24
        router:
          name: cm-pub-router
  instances:
    instance:
      name: cmts-inst1
      flavor: m1.small
      ports:
        - port:
            name: cmts-inst-1-port
            network_name: public
            ip: 10.197.122.10
      ansible:
