---
- hosts: all
  sudo: yes

  tasks:
   - yum: name=net-tools
   - yum: name=wget
   - yum: name=git
   - yum: name=libvirt-python
   - yum: name=python-docutils
   - yum: name=libvirt
   - yum: name=qemu-kvm
   - yum: name=libguestfs-tools
   - yum: name=rpm-build

   - name: Yum Config Manager
     command: yum-config-manager --enable rhelosp-rhel-7-server-opt

   - yum: name=epel-release

   # This should probably reflect Mikita
   - name: Liberty Repo
     command: curl -o /etc/yum.repos.d/delorean-liberty.repo https://trunk.rdoproject.org/centos7-liberty/current/delorean.repo

   - yum: name=yum-plugin-priorities
   - yum: name=openstack-tripleo

   - name: Install PIP
     command: easy_install pip

   - pip: virtualenv


